version: "3.7"
services:
  node-backend:
    build: ./api
    container_name: node-backend
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
