version: "3"

services:
  node-backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - node-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
